### Signup
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
  "username": "test@gmail.com",
  "first_name": "test",
  "password": "123"
}

### Login
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "123"
}

###
# Get JWT Token and set the token variable
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "hello@gmail.com",
  "password": "741"
} 
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MjkyNzk3LCJpYXQiOjE3MTkyMDYzOTcsImp0aSI6ImFjNjZmMWI0YjE1MTQ5MzA4NTAwYzBhNzE1YTE4OTgzIiwidXNlcl9pZCI6Mn0.0GMQM-zpf4NN4tSOZMc98ACZTq-zIU1kgXP7Hi8Z1Wo
###

### Create Event
POST http://127.0.0.1:8000/events/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Sample Event",
  "description": "This is a sample event.",
  "date": "2024-07-01",
  "time": "12:30:00",
  "capacity": 100,
  "user": 2
}

### List Events
GET http://127.0.0.1:8000/events/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Event Detail (replace EVENT_ID with the actual event ID)
GET http://127.0.0.1:8000/events/10/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Update Event (replace EVENT_ID with the actual event ID)
PUT http://127.0.0.1:8000/events/10/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Event Title",
  "description": "Updated description.",
  "date": "1645-12-12",
  "time": "00:01:00",
  "capacity": 150,
  "user": 2
}

### Delete Event (replace EVENT_ID with the actual event ID)
DELETE http://127.0.0.1:8000/events/6/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Book Event (replace EVENT_ID with the actual event ID)
POST http://127.0.0.1:8000/bookings/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "event_id": 9
}

###
### List Bookings
GET http://127.0.0.1:8000/user/events/
Authorization: Bearer {{token}}
