### Signup
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
  "username": "test@gmail.com",
  "first_name": "test",
  "password": "123"
}

### Login
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "123"
}

###

# Get JWT Token and set the token variable
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "hello@gmail.com",
  "password": "741"
} 
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MjQ3NzE4LCJpYXQiOjE3MTkxNjEzMTgsImp0aSI6IjcyNWFjOWFhNmNhYzQ0NDZhMjc5MzFhYTE0MDIwY2IwIiwidXNlcl9pZCI6NH0.VsN8Dbw_orjxoiuBJXuRWF_rMdxEYYUOP0z6AXkpDJI

###

### Create Event
POST http://127.0.0.1:8000/events/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Sample Event",
  "description": "This is a sample event.",
  "date": "2024-07-01",
  "time": "12:30:00",
  "capacity": 100,
  "user": 2
}

### List Events
GET http://127.0.0.1:8000/events/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Event Detail (replace EVENT_ID with the actual event ID)
GET http://127.0.0.1:8000/events/1/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Update Event (replace EVENT_ID with the actual event ID)
PUT http://127.0.0.1:8000/events/1/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Event Title",
  "description": "Updated description.",
  "date": "2024-07-01T14:00:00Z",
  "capacity": 150,
  "user": 2
}

### Delete Event (replace EVENT_ID with the actual event ID)
DELETE http://127.0.0.1:8000/events/2/
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Book Event (replace EVENT_ID with the actual event ID)
POST http://127.0.0.1:8000/bookings/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "event": 1
}

